version: "3.9"
services:
  db:
    image: postgres:15.3-alpine
    container_name: db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - LANG=en_US.utf8
      - LC_ALL=en_US.utf8
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always

  myagilos:
    image: myagilos:1.0.0
    container_name: myagilos
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - ADMINS=${ADMINS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - HTTPS_ON=${HTTPS_ON}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE}
      - CSRF_COOKIE_SECURE=${CSRF_COOKIE_SECURE}
      - SECURE_SSL_REDIRECT=${SECURE_SSL_REDIRECT}
      - HSTS_ON=${HSTS_ON}
      - SECURE_HSTS_SECONDS=${SECURE_HSTS_SECONDS}
      - SECURE_HSTS_PRELOAD=${SECURE_HSTS_PRELOAD}
      - SECURE_HSTS_INCLUDE_SUBDOMAINS=${SECURE_HSTS_INCLUDE_SUBDOMAINS}
      - SESSION_COOKIE_AGE=${SESSION_COOKIE_AGE}
      - HR_MAIL=${HR_MAIL}
      - MANAGER_MAIL=${MANAGER_MAIL}
      - MKT_MAIL=${MKT_MAIL}
      - MAIL_SENDER=${MAIL_SENDER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENDING=${MAIL_ENDING}
      - DEBUG=${DEBUG}
    depends_on:
      - db
    restart: always

  proxy:
    image: myagilos-proxy:1.0.0
    container_name: myagilos-proxy
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - 80:8000
    depends_on:
      - myagilos
    restart: always

volumes:
  static_data:
  postgresql_data: