version: "3.9"
services:
  myagilos:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./myagilos_proposal:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1