version: "3.9"
services:
  db:
    image: postgres:15.3-alpine
    container_name: db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - LANG=en_US.utf8
      - LC_ALL=en_US.utf8
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always

  myagilos:
    image: myagilos:1.0.0
    container_name: myagilos
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - ALLOWED_HOSTS=ec2-13-48-56-186.eu-north-1.compute.amazonaws.com
      - DB_HOST=db
      - DB_NAME=n
      - DB_USER=u
      - DB_PASS=p
      - SECRET_KEY=sss
      - HR_MAIL=${HR_MAIL}
      - MANAGER_MAIL=${MANAGER_MAIL}
      - MKT_MAIL=${MKT_MAIL}
      - MAIL_SENDER=${MAIL_SENDER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENDING=${MAIL_ENDING}
      - DEBUG=${DEBUG}
    depends_on:
      - db
    restart: always

  proxy:
    image: myagilos-proxy:1.0.0
    container_name: myagilos-proxy
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - 80:8000
    depends_on:
      - myagilos
    restart: always

volumes:
  static_data:
  postgresql_data: