# Generated by Django 4.1.7 on 2023-04-11 09:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="certifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="consultant_certifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("earned_at", models.DateTimeField()),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultants.certifications",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="consultants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=30)),
                ("last", models.CharField(max_length=30)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "certifications",
                    models.ManyToManyField(
                        related_name="related_consultants",
                        through="consultants.consultant_certifications",
                        to="consultants.certifications",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consultant_certifications",
            name="consultant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="consultants.consultants",
            ),
        ),
        migrations.AddField(
            model_name="certifications",
            name="consultants",
            field=models.ManyToManyField(
                related_name="related_certifications",
                through="consultants.consultant_certifications",
                to="consultants.consultants",
            ),
        ),
        migrations.CreateModel(
            name="certification_targets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_year",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(2022),
                            django.core.validators.MaxValueValidator(2023),
                        ],
                    ),
                ),
                ("active", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target",
                        to="consultants.certifications",
                        unique_for_year="created_at",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="certification_progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("achieved", models.BooleanField()),
                ("achieved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="consultants.consultants",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="consultants.certification_targets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("industry", models.CharField(max_length=64)),
                ("company", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "year",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(2022),
                            django.core.validators.MaxValueValidator(2023),
                        ],
                    ),
                ),
                ("project_start", models.DateField()),
                ("project_end", models.DateField()),
                ("gpt_content", models.TextField(max_length=1500)),
                ("issue", models.CharField(max_length=400)),
                ("architecture", models.CharField(max_length=400)),
                ("challenge", models.CharField(max_length=400)),
                ("solution", models.CharField(max_length=400)),
                ("tools", models.CharField(max_length=400)),
                ("why_agilos", models.CharField(max_length=400)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case",
                        to="consultants.consultants",
                    ),
                ),
            ],
        ),
    ]
