# Generated by Django 4.1.7 on 2023-04-11 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cases",
            options={"verbose_name_plural": "cases"},
        ),
        migrations.AlterModelOptions(
            name="certification_progress",
            options={"verbose_name_plural": "certification_progress"},
        ),
        migrations.AlterModelOptions(
            name="certification_targets",
            options={"verbose_name_plural": "certification_targets"},
        ),
        migrations.AlterModelOptions(
            name="certifications",
            options={"verbose_name_plural": "certifications"},
        ),
        migrations.AlterModelOptions(
            name="consultant_certifications",
            options={"verbose_name_plural": "consultant_certifications"},
        ),
        migrations.AlterModelOptions(
            name="consultants",
            options={"verbose_name_plural": "consultants"},
        ),
    ]
