# Generated by Django 4.1.7 on 2023-04-12 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0003_consultants_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="consultant_certifications",
            unique_together={("consultant", "certification")},
        ),
    ]
