# Generated by Django 4.1.7 on 2023-04-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0004_alter_consultant_certifications_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certifications",
            name="consultants",
            field=models.ManyToManyField(
                related_name="related_certifications",
                through="consultants.Consultant_certifications",
                to="consultants.consultants",
            ),
        ),
        migrations.AlterField(
            model_name="consultants",
            name="certifications",
            field=models.ManyToManyField(
                related_name="related_consultants",
                through="consultants.Consultant_certifications",
                to="consultants.certifications",
            ),
        ),
    ]
