# Generated by Django 4.1.7 on 2023-04-12 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("consultants", "0007_alter_consultants_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultants",
            options={"verbose_name_plural": "consultants"},
        ),
        migrations.AlterModelManagers(
            name="consultants",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="consultants",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="consultants",
            name="email",
        ),
        migrations.RemoveField(
            model_name="consultants",
            name="first",
        ),
        migrations.RemoveField(
            model_name="consultants",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="consultants",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="consultants",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="consultants",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="consultants",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="consultants",
            name="last",
        ),
        migrations.RemoveField(
            model_name="consultants",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="consultants",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="consultants",
            name="password",
        ),
        migrations.RemoveField(
            model_name="consultants",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="consultants",
            name="username",
        ),
        migrations.AddField(
            model_name="consultants",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="as_consultant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
