# Generated by Django 4.1.7 on 2023-04-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "consultants",
            "0008_alter_consultants_options_alter_consultants_managers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="consultants",
            name="target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="consultants.certification_targets",
            ),
        ),
    ]
