# Generated by Django 4.1.7 on 2023-04-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0010_consultants_first_consultants_last"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultants",
            name="first",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="consultants",
            name="last",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
