# Generated by Django 4.1.7 on 2023-04-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0012_alter_consultants_first_alter_consultants_last"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultants",
            name="first",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="consultants",
            name="last",
            field=models.CharField(max_length=30),
        ),
    ]
