# Generated by Django 4.1.7 on 2023-04-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0013_alter_consultants_first_alter_consultants_last"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultants",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="consultants.certification_targets",
            ),
        ),
    ]
