# Generated by Django 4.1.7 on 2023-04-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0014_alter_consultants_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultants",
            name="email",
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
    ]
