# Generated by Django 4.1.7 on 2023-04-12 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0015_consultants_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consultants",
            old_name="first",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="consultants",
            old_name="last",
            new_name="last_name",
        ),
    ]
