# Generated by Django 4.1.7 on 2023-04-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0016_rename_first_consultants_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification_targets",
            name="target_year",
            field=models.PositiveSmallIntegerField(default=2023, editable=False),
        ),
    ]
