# Generated by Django 4.1.7 on 2023-04-13 10:22

import consultants.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0017_alter_certification_targets_target_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cases",
            options={"verbose_name_plural": "Cases"},
        ),
        migrations.AlterModelOptions(
            name="certification_progress",
            options={"verbose_name_plural": "Certification_progress"},
        ),
        migrations.AlterModelOptions(
            name="certification_targets",
            options={"verbose_name_plural": "Certification_targets"},
        ),
        migrations.AlterModelOptions(
            name="certifications",
            options={"verbose_name_plural": "Certifications"},
        ),
        migrations.AlterModelOptions(
            name="consultant_certifications",
            options={"verbose_name_plural": "Consultant_certifications"},
        ),
        migrations.AlterModelOptions(
            name="consultants",
            options={"verbose_name_plural": "Consultants"},
        ),
        migrations.AddField(
            model_name="certification_targets",
            name="semester",
            field=models.PositiveSmallIntegerField(
                default=consultants.models.semester_num
            ),
        ),
        migrations.AlterField(
            model_name="certification_targets",
            name="target_year",
            field=models.PositiveSmallIntegerField(default=2023),
        ),
    ]
