# Generated by Django 4.1.7 on 2023-04-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0019_alter_cases_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant_certifications",
            name="earned_at",
            field=models.DateField(),
        ),
    ]
