# Generated by Django 4.1.7 on 2023-04-18 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0020_alter_consultant_certifications_earned_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="certification_progress",
            unique_together={("consultant", "target", "achieved")},
        ),
    ]
