# Generated by Django 4.1.7 on 2023-04-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0021_alter_certification_progress_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification_targets",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
