# Generated by Django 4.1.7 on 2023-04-18 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0022_alter_certification_targets_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="certification_progress",
            unique_together={("consultant", "target")},
        ),
    ]
