# Generated by Django 4.1.7 on 2023-04-18 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0023_alter_certification_progress_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certification_progress",
            old_name="achieved_at",
            new_name="created_at",
        ),
    ]
