# Generated by Django 4.1.7 on 2023-04-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0024_rename_achieved_at_certification_progress_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cases",
            name="gpt_content",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="cases",
            name="industry",
            field=models.CharField(
                choices=[
                    ("---", "---"),
                    ("Aerospace and Defense", "Aerospace and Defense"),
                    ("Agriculture", "Agriculture"),
                    ("Automotive", "Automotive"),
                    ("Bank", "Bank"),
                    ("Construction", "Construction"),
                    ("Education", "Education"),
                    ("Energy", "Energy"),
                    (
                        "Environmental Conservation and Sustainability",
                        "Environmental Conservation and Sustainability",
                    ),
                    ("Finance", "Finance"),
                    (
                        "Government and Public Administration",
                        "Government and Public Administration",
                    ),
                    ("Health", "Health"),
                    ("Hospitality", "Hospitality"),
                    ("Insurance", "Insurance"),
                    ("Law and Legal Services", "Law and Legal Services"),
                    ("Manufacturing", "Manufacturing"),
                    ("Media and Entertainment", "Media and Entertainment"),
                    ("Nonprofit ans Social Services", "Nonprofit ans Social Services"),
                    ("Pharmaceuticals", "Pharmaceuticals"),
                    ("Real Estate", "Real Estate"),
                    ("Retail", "Retail"),
                    ("Sports and Fitness", "Sports and Fitness"),
                    ("Telecommunications", "Telecommunications"),
                    ("Technology", "Technology"),
                    ("Transportation", "Transportation"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="certifications",
            name="company",
            field=models.CharField(
                choices=[
                    ("Microsoft", "Microsoft"),
                    ("Snowflake", "Snowflake"),
                    ("Qlik", "Qlik"),
                ],
                max_length=64,
            ),
        ),
    ]
