# Generated by Django 4.1.7 on 2023-05-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0025_alter_cases_gpt_content_alter_cases_industry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForgotPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="cases",
            name="architecture",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="cases",
            name="challenge",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="cases",
            name="issue",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="cases",
            name="solution",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="cases",
            name="tools",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="cases",
            name="why_agilos",
            field=models.TextField(max_length=400),
        ),
    ]
