# Generated by Django 4.1.7 on 2023-05-04 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultants", "0026_forgotpassword_alter_cases_architecture_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forgotpassword",
            name="token",
        ),
        migrations.AddField(
            model_name="forgotpassword",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 4, 14, 20, 25, 337970, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="forgotpassword",
            name="salt_and_hash",
            field=models.CharField(blank=True, max_length=126, null=True, unique=True),
        ),
    ]
